# Generated by Django 5.0.6 on 2024-07-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.AlterField(
            model_name='profile',
            name='category_quota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='domicile_certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
