# Generated by Django 5.0.6 on 2024-07-03 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_remove_application_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='in_merit_list',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applications', models.ManyToManyField(to='admissions.application')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program')),
            ],
        ),
    ]
