# Generated by Django 5.0.6 on 2024-07-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_application_in_merit_list_meritlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritlist',
            name='published',
        ),
    ]
