# Generated by Django 5.0.6 on 2024-07-04 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_remove_meritlist_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meritlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
