# Generated by Django 5.0.6 on 2024-08-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_remove_profile_profile_image_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_image',
        ),
    ]
