# Generated by Django 5.0.6 on 2024-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_rename_image_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='merit_list_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='merit_list_generated',
            field=models.BooleanField(default=False),
        ),
    ]
