# Generated by Django 5.0.6 on 2024-09-03 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='academic_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='in_merit_list',
        ),
        migrations.RemoveField(
            model_name='application',
            name='merit_list_batch',
        ),
        migrations.RemoveField(
            model_name='application',
            name='merit_list_generated',
        ),
        migrations.RemoveField(
            model_name='application',
            name='personal_details',
        ),
        migrations.CreateModel(
            name='BSApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_selection', models.CharField(max_length=100)),
                ('program_selection', models.CharField(choices=[('BBA Hons', 'BBA Hons'), ('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('English', 'English')], max_length=100)),
                ('employment_status', models.CharField(choices=[('Serving Armed Forces', 'Serving Armed Forces'), ('Serving FGEI Employee', 'Serving FGEI Employee'), ('Retired Armed Forces', 'Retired Armed Forces'), ('Civilian', 'Civilian'), ('Defence Paid', 'Defence Paid'), ('Ward of Shuhada', 'Ward of Shuhada'), ('Sports Quota', 'Sports Quota'), ('Disability Quota', 'Disability Quota')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passed', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('roll_no', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('major_subject', models.CharField(max_length=100)),
                ('father_cnic', models.CharField(max_length=15)),
                ('relationship_to_student', models.CharField(blank=True, max_length=50, null=True)),
                ('father_profession', models.CharField(max_length=100)),
                ('father_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('father_whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FAApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_choice', models.CharField(choices=[('Arts', 'Arts'), ('Humanities', 'Humanities')], max_length=50)),
                ('employment_status', models.CharField(choices=[('Serving Armed Forces', 'Serving Armed Forces'), ('Serving FGEI Employee', 'Serving FGEI Employee'), ('Retired Armed Forces', 'Retired Armed Forces'), ('Civilian', 'Civilian'), ('Defence Paid', 'Defence Paid'), ('Ward of Shuhada', 'Ward of Shuhada'), ('Sports Quota', 'Sports Quota'), ('Disability Quota', 'Disability Quota')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passed', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('roll_no', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('major_subject', models.CharField(max_length=100)),
                ('father_cnic', models.CharField(max_length=15)),
                ('relationship_to_student', models.CharField(blank=True, max_length=50, null=True)),
                ('father_profession', models.CharField(max_length=100)),
                ('father_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('father_whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FSCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_choice', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Political Science', 'Political Science'), ('English', 'English')], max_length=50)),
                ('employment_status', models.CharField(choices=[('Serving Armed Forces', 'Serving Armed Forces'), ('Serving FGEI Employee', 'Serving FGEI Employee'), ('Retired Armed Forces', 'Retired Armed Forces'), ('Civilian', 'Civilian'), ('Defence Paid', 'Defence Paid'), ('Ward of Shuhada', 'Ward of Shuhada'), ('Sports Quota', 'Sports Quota'), ('Disability Quota', 'Disability Quota')], max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('exam_passed', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('roll_no', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=100)),
                ('major_subject', models.CharField(max_length=100)),
                ('father_cnic', models.CharField(max_length=15)),
                ('relationship_to_student', models.CharField(blank=True, max_length=50, null=True)),
                ('father_profession', models.CharField(max_length=100)),
                ('father_contact_number', models.CharField(max_length=15)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('father_whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.profile')),
            ],
        ),
    ]
