# Generated by Django 5.0.6 on 2024-09-03 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_rename_submitted_at_application_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category_quota',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='domicile_certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intermediate_certificate_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matric_certificate_details',
        ),
    ]
