# Generated by Django 5.0.6 on 2024-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_remove_profile_category_quota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faapplication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='fscapplication',
            name='profile',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='application',
            name='academic_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='in_merit_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='merit_list_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='merit_list_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='category_quota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='domicile_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediate_certificate_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_certificate_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BSApplication',
        ),
        migrations.DeleteModel(
            name='FAApplication',
        ),
        migrations.DeleteModel(
            name='FSCApplication',
        ),
    ]
