# Generated by Django 5.0.6 on 2024-09-15 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_bsapplication_faapplication_fscapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
        migrations.AddField(
            model_name='faapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
        migrations.AddField(
            model_name='fscapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
    ]
