# Generated by Django 5.0.6 on 2024-09-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0019_bsapplication_profile_faapplication_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritlist',
            name='bs_applications',
        ),
        migrations.RemoveField(
            model_name='faapplication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='fa_applications',
        ),
        migrations.RemoveField(
            model_name='fscapplication',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='fsc_applications',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='program_type',
        ),
        migrations.AddField(
            model_name='meritlist',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.program'),
        ),
        migrations.AddField(
            model_name='profile',
            name='category_quota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='domicile_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediate_certificate_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_certificate_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_list_generated', models.BooleanField(default=False)),
                ('merit_list_batch', models.IntegerField(blank=True, null=True)),
                ('academic_details', models.TextField(blank=True, null=True)),
                ('personal_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('in_merit_list', models.BooleanField(default=False)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.college')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meritlist',
            name='applications',
            field=models.ManyToManyField(to='admissions.application'),
        ),
        migrations.DeleteModel(
            name='BSApplication',
        ),
        migrations.DeleteModel(
            name='FAApplication',
        ),
        migrations.DeleteModel(
            name='FSCApplication',
        ),
    ]
