# Generated by Django 5.0.6 on 2024-09-15 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_remove_meritlist_bs_applications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_selection', models.CharField(choices=[('BBA Hons', 'BBA Hons'), ('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('English', 'English')], max_length=100)),
                ('employment_status', models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], max_length=30)),
                ('cnic', models.CharField(max_length=15)),
                ('domicile', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('certificate_degree_level', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('obtained_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('roll_no', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('major_subject', models.CharField(max_length=100)),
                ('father_cnic', models.CharField(max_length=15)),
                ('relationship_to_student', models.CharField(blank=True, max_length=50, null=True)),
                ('father_profession', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_number', models.CharField(blank=True, max_length=15, null=True)),
                ('father_whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('attested_photocopy_hssc', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('attested_photocopy_father_mother_cnic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('attested_photocopy_candidate_cnic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('provisional_character_certificate', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('original_migration_certificate', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('passport_photographs', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('proof_employment_status_parents', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('affidavit_district_court', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FAApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_selection', models.CharField(choices=[('Arts', 'Arts'), ('Humanities', 'Humanities')], max_length=100)),
                ('employment_status', models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], max_length=30)),
                ('cnic', models.CharField(max_length=15)),
                ('domicile', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('ssc_registration_number', models.CharField(max_length=20)),
                ('last_school_attended', models.CharField(max_length=100)),
                ('year_of_passing', models.IntegerField()),
                ('roll_no', models.CharField(max_length=20)),
                ('marks_obtained', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('marks_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('div_grade', models.CharField(max_length=5)),
                ('board', models.CharField(max_length=50)),
                ('attested_photocopy_hssc', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('attested_photocopy_father_mother_cnic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('attested_photocopy_candidate_cnic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('provisional_character_certificate', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('original_migration_certificate', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('passport_photographs', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('proof_employment_status_parents', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('affidavit_district_court', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FSCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_selection', models.CharField(choices=[('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('medical', 'Medical')], max_length=100)),
                ('employment_status', models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], max_length=30)),
                ('cnic', models.CharField(max_length=15)),
                ('domicile', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('ssc_registration_number', models.CharField(max_length=20)),
                ('last_school_attended', models.CharField(max_length=100)),
                ('year_of_passing_ssc', models.IntegerField()),
                ('ssc_roll_no', models.CharField(max_length=20)),
                ('ssc_marks_obtained', models.IntegerField()),
                ('ssc_max_marks', models.IntegerField()),
                ('ssc_marks_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ssc_div_grade', models.CharField(max_length=5)),
                ('ssc_board', models.CharField(max_length=50)),
                ('attested_photocopy_hssc', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('attested_photocopy_father_mother_cnic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('attested_photocopy_candidate_cnic', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('provisional_character_certificate', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('original_migration_certificate', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('passport_photographs', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('proof_employment_status_parents', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('affidavit_district_court', models.ImageField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='applications',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='program',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category_quota',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='domicile_certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intermediate_certificate_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matric_certificate_details',
        ),
        migrations.AddField(
            model_name='bsapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
        migrations.AddField(
            model_name='faapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
        migrations.AddField(
            model_name='fscapplication',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='MeritList',
        ),
    ]
