# Generated by Django 5.0.6 on 2024-09-16 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_announcement_remove_faapplication_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='academic_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='college',
        ),
        migrations.RemoveField(
            model_name='application',
            name='in_merit_list',
        ),
        migrations.RemoveField(
            model_name='application',
            name='personal_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category_quota',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='domicile_certificate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intermediate_certificate_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='matric_certificate_details',
        ),
        migrations.AddField(
            model_name='application',
            name='affidavit_district_court',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='attested_photocopy_candidate_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='attested_photocopy_father_mother_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='attested_photocopy_hssc',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='bs_subject',
            field=models.CharField(blank=True, choices=[('BBA Hons', 'BBA Hons'), ('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('English', 'English')], default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='certificate_degree_level',
            field=models.CharField(blank=True, default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='cnic',
            field=models.CharField(default='0000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='domicile',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], default='civilian', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='fa_subject',
            field=models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Humanities', 'Humanities')], default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='father_cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='father_profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='father_whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fsc_subject',
            field=models.CharField(blank=True, choices=[('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('Medical', 'Medical')], default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='hssc_board',
            field=models.CharField(blank=True, default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='hssc_marks_obtained',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hssc_marks_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hssc_max_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hssc_roll_no',
            field=models.CharField(blank=True, default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='last_school_attended',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='original_migration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photographs',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.profile'),
        ),
        migrations.AddField(
            model_name='application',
            name='proof_employment_status_parents',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='provisional_character_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='application',
            name='relationship_to_student',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='religion',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_board',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_div_grade',
            field=models.CharField(default='Unknown', max_length=5),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_marks_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_max_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_registration_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='ssc_roll_no',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='year_of_passing_hssc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='year_of_passing_ssc',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.program'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='No Address Provided'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='No Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(choices=[('FA', 'FA'), ('FSC', 'FSC'), ('BS', 'BS')], max_length=100, unique=True),
        ),
    ]
