# Generated by Django 5.0.6 on 2024-09-16 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0023_remove_application_academic_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='affidavit_district_court',
        ),
        migrations.RemoveField(
            model_name='application',
            name='attested_photocopy_candidate_cnic',
        ),
        migrations.RemoveField(
            model_name='application',
            name='attested_photocopy_father_mother_cnic',
        ),
        migrations.RemoveField(
            model_name='application',
            name='attested_photocopy_hssc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='bs_subject',
        ),
        migrations.RemoveField(
            model_name='application',
            name='certificate_degree_level',
        ),
        migrations.RemoveField(
            model_name='application',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='application',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='domicile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fa_subject',
        ),
        migrations.RemoveField(
            model_name='application',
            name='father_cnic',
        ),
        migrations.RemoveField(
            model_name='application',
            name='father_profession',
        ),
        migrations.RemoveField(
            model_name='application',
            name='father_whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='fsc_subject',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hssc_board',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hssc_marks_obtained',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hssc_marks_percentage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hssc_max_marks',
        ),
        migrations.RemoveField(
            model_name='application',
            name='hssc_roll_no',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_school_attended',
        ),
        migrations.RemoveField(
            model_name='application',
            name='original_migration_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='passport_photographs',
        ),
        migrations.RemoveField(
            model_name='application',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='application',
            name='proof_employment_status_parents',
        ),
        migrations.RemoveField(
            model_name='application',
            name='provisional_character_certificate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='relationship_to_student',
        ),
        migrations.RemoveField(
            model_name='application',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_board',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_div_grade',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_marks_obtained',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_marks_percentage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_max_marks',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_registration_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ssc_roll_no',
        ),
        migrations.RemoveField(
            model_name='application',
            name='year_of_passing_hssc',
        ),
        migrations.RemoveField(
            model_name='application',
            name='year_of_passing_ssc',
        ),
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='academic_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admissions.college'),
        ),
        migrations.AddField(
            model_name='application',
            name='in_merit_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='personal_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='category_quota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='domicile_certificate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intermediate_certificate_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='matric_certificate_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
