# Generated by Django 5.0.6 on 2024-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0027_remove_meritlist_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='faapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='fscapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
