# Generated by Django 5.0.6 on 2024-09-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0028_bsapplication_status_faapplication_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritlist',
            name='merit_list_generated',
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='program',
            field=models.CharField(max_length=100),
        ),
    ]
