# Generated by Django 5.0.6 on 2024-09-18 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0029_remove_meritlist_merit_list_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fscapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
