# Generated by Django 5.0.6 on 2024-09-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0030_bsapplication_created_at_faapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='faapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='fscapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
