# Generated by Django 5.0.6 on 2024-09-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0031_bsapplication_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=10),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=10),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=10),
        ),
    ]
