# Generated by Django 5.0.6 on 2024-10-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0032_alter_bsapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
