# Generated by Django 5.0.6 on 2024-10-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0033_profile_is_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
    ]
