# Generated by Django 5.0.6 on 2024-10-03 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0034_remove_profile_is_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='affidavit_district_court',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Affidavit District Court'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='attested_photocopy_candidate_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy Candidate CNIC'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='attested_photocopy_father_mother_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy Father/Mother CNIC'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='attested_photocopy_hssc',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy HSSC'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='board',
            field=models.CharField(max_length=100, verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='certificate_degree_level',
            field=models.CharField(max_length=100, verbose_name='Certificate/Degree Level'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='cnic',
            field=models.CharField(max_length=15, verbose_name='CNIC'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='college_selection',
            field=models.CharField(default='FG College', max_length=100, verbose_name='College Selection'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='contact_number',
            field=models.CharField(max_length=15, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='domicile',
            field=models.CharField(max_length=100, verbose_name='Domicile'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Emergency Number'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], max_length=30, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='father_cnic',
            field=models.CharField(max_length=15, verbose_name="Father's CNIC"),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='father_profession',
            field=models.CharField(max_length=100, verbose_name="Father's Profession"),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='father_whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Father's WhatsApp Number"),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='major_subject',
            field=models.CharField(max_length=100, verbose_name='Major Subject'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='obtained_marks',
            field=models.IntegerField(verbose_name='Obtained Marks'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='original_migration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Original Migration Certificate'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='passport_photographs',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Passport Photographs'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='Payment Screenshot'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='program_selection',
            field=models.CharField(choices=[('BBA Hons', 'BBA Hons'), ('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('English', 'English')], max_length=100, verbose_name='Program Selection'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='proof_employment_status_parents',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Proof of Employment Status of Parents'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='provisional_character_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Provisional Character Certificate'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='relationship_to_student',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship to Student'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='religion',
            field=models.CharField(max_length=50, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='roll_no',
            field=models.CharField(max_length=100, verbose_name='Roll Number'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='total_marks',
            field=models.IntegerField(verbose_name='Total Marks'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bsapplication',
            name='year_of_passing',
            field=models.IntegerField(verbose_name='Year of Passing'),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=255, verbose_name='College Name'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='affidavit_district_court',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Affidavit District Court'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='attested_photocopy_candidate_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy Candidate CNIC'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='attested_photocopy_father_mother_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy Father/Mother CNIC'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='attested_photocopy_hssc',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy HSSC'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='board',
            field=models.CharField(max_length=50, verbose_name='Board'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='cnic',
            field=models.CharField(max_length=15, verbose_name='CNIC'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='college_selection',
            field=models.CharField(default='FG College', max_length=100, verbose_name='College Selection'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='div_grade',
            field=models.CharField(max_length=5, verbose_name='Division/Grade'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='domicile',
            field=models.CharField(max_length=100, verbose_name='Domicile'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], max_length=30, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='last_school_attended',
            field=models.CharField(max_length=100, verbose_name='Last School Attended'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='marks_obtained',
            field=models.IntegerField(verbose_name='Marks Obtained'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='marks_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marks Percentage'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='max_marks',
            field=models.IntegerField(verbose_name='Max Marks'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='original_migration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Original Migration Certificate'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='passport_photographs',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Passport Photographs'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='Payment Screenshot'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='program_selection',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Humanities', 'Humanities')], max_length=100, verbose_name='Program Selection'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='proof_employment_status_parents',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Proof of Employment Status of Parents'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='provisional_character_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Provisional Character Certificate'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='religion',
            field=models.CharField(max_length=50, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='roll_no',
            field=models.CharField(max_length=20, verbose_name='Roll Number'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='ssc_registration_number',
            field=models.CharField(max_length=20, verbose_name='SSC Registration Number'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='year_of_passing',
            field=models.IntegerField(verbose_name='Year of Passing'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='affidavit_district_court',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Affidavit District Court'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='attested_photocopy_candidate_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy Candidate CNIC'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='attested_photocopy_father_mother_cnic',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy Father/Mother CNIC'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='attested_photocopy_hssc',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Attested Photocopy HSSC'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='cnic',
            field=models.CharField(max_length=15, verbose_name='CNIC'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='college_selection',
            field=models.CharField(default='FG College', max_length=100, verbose_name='College Selection'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='domicile',
            field=models.CharField(max_length=100, verbose_name='Domicile'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada'), ('sports_quota', 'Sports Quota'), ('disability_quota', 'Disability Quota')], max_length=30, verbose_name='Employment Status'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='last_school_attended',
            field=models.CharField(max_length=100, verbose_name='Last School Attended'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='original_migration_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Original Migration Certificate'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='passport_photographs',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Passport Photographs'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='Payment Screenshot'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='program_selection',
            field=models.CharField(choices=[('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('medical', 'Medical')], max_length=100, verbose_name='Program Selection'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='proof_employment_status_parents',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Proof of Employment Status of Parents'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='provisional_character_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='Provisional Character Certificate'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='religion',
            field=models.CharField(max_length=50, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_board',
            field=models.CharField(max_length=50, verbose_name='SSC Board'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_div_grade',
            field=models.CharField(max_length=5, verbose_name='SSC Division/Grade'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_marks_obtained',
            field=models.IntegerField(verbose_name='SSC Marks Obtained'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_marks_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SSC Marks Percentage'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_max_marks',
            field=models.IntegerField(verbose_name='SSC Max Marks'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_registration_number',
            field=models.CharField(max_length=20, verbose_name='SSC Registration Number'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='ssc_roll_no',
            field=models.CharField(max_length=20, verbose_name='SSC Roll Number'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='status',
            field=models.CharField(default='submitted', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='year_of_passing_ssc',
            field=models.IntegerField(verbose_name='Year of Passing SSC'),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='bs_applications',
            field=models.ManyToManyField(blank=True, to='admissions.bsapplication', verbose_name='BS Applications'),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='fa_applications',
            field=models.ManyToManyField(blank=True, to='admissions.faapplication', verbose_name='FA Applications'),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='fsc_applications',
            field=models.ManyToManyField(blank=True, to='admissions.fscapplication', verbose_name='FSC Applications'),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='merit_list_batch',
            field=models.IntegerField(blank=True, null=True, verbose_name='Merit List Batch'),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='program',
            field=models.CharField(max_length=100, verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Program Name'),
        ),
    ]
