# Generated by Django 5.0.6 on 2024-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0036_alter_announcement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlist',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
