# Generated by Django 5.0.6 on 2024-10-05 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0037_meritlist_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritlist',
            name='subject',
        ),
    ]
