# Generated by Django 5.0.6 on 2024-10-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0038_remove_meritlist_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlist',
            name='subject',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
