# Generated by Django 5.0.6 on 2024-10-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0039_meritlist_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
