# Generated by Django 5.0.6 on 2024-10-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0040_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsapplication',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faapplication',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fscapplication',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled')], max_length=20, null=True),
        ),
    ]
