# Generated by Django 5.0.6 on 2024-10-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0041_bsapplication_quota_faapplication_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsapplication',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='employment_status',
            field=models.CharField(choices=[('serving_armed_forces', 'Serving Armed Forces'), ('serving_fgei_employee', 'Serving FGEI Employee'), ('retired_armed_forces', 'Retired Armed Forces'), ('civilian', 'Civilian'), ('defence_paid', 'Defence Paid'), ('ward_of_shuhada', 'Ward of Shuhada')], max_length=30),
        ),
    ]
