# Generated by Django 5.0.6 on 2024-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0042_alter_bsapplication_employment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritlist',
            name='merit_list_batch',
        ),
        migrations.RemoveField(
            model_name='meritlist',
            name='subject',
        ),
        migrations.AddField(
            model_name='meritlist',
            name='list_type',
            field=models.CharField(choices=[('open', 'Open Merit'), ('quota', 'Quota Based')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='percentage_cutoff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled'), ('sports', 'Sports')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='program',
            field=models.CharField(choices=[('FA', 'FA'), ('FSC', 'FSC'), ('BS', 'BS')], max_length=10),
        ),
    ]
