# Generated by Django 5.0.6 on 2024-10-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0043_remove_meritlist_merit_list_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faapplication',
            name='marks_percentage',
        ),
        migrations.RemoveField(
            model_name='fscapplication',
            name='ssc_marks_percentage',
        ),
    ]
