# Generated by Django 5.0.6 on 2024-10-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0044_remove_faapplication_marks_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlist',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
