# Generated by Django 5.0.6 on 2024-10-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0045_meritlist_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
