# Generated by Django 5.0.6 on 2024-10-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0046_admissionstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bsapplication',
            old_name='obtained_marks',
            new_name='marks_obtained',
        ),
        migrations.RenameField(
            model_name='bsapplication',
            old_name='total_marks',
            new_name='max_marks',
        ),
        migrations.RenameField(
            model_name='fscapplication',
            old_name='ssc_marks_obtained',
            new_name='marks_obtained',
        ),
        migrations.RenameField(
            model_name='fscapplication',
            old_name='ssc_max_marks',
            new_name='max_marks',
        ),
    ]
