# Generated by Django 5.0.6 on 2024-10-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0047_rename_obtained_marks_bsapplication_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='program',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
