# Generated by Django 5.0.6 on 2024-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0048_program_is_open_program_subject_alter_program_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsapplication',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled'), ('sports', 'Sports')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='faapplication',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled'), ('sports', 'Sports')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fscapplication',
            name='quota',
            field=models.CharField(blank=True, choices=[('army_retired', 'Army Retired'), ('hafiz_e_quran', 'Hafiz-e-Quran'), ('disabled', 'Disabled'), ('sports', 'Sports')], max_length=20, null=True),
        ),
    ]
