# Generated by Django 5.0.6 on 2024-10-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0049_alter_bsapplication_quota_alter_faapplication_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlist',
            name='available_seats',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
